### ISSUE TITLE
Stylus boostrap loaded but not compiled with Webpack

### ISSUE THREAD

**Issue by oric01** [maxmx/bootstrap-stylus#122]
Hi,

```
    "bootstrap-styl": "^5.0.5",
    "stylus": "^0.54.5",
    "stylus-loader": "^2.0.0",
    "webpack": "^1.9.5",
```

Im trying to use bootstrap-stylus in a Webpack context.
As far as I understand, bootstrap-stylus is a Stylus plugin so i used this config in order to parse bootstrap stylus files : 

```
//webpack.config.js
module.exports = {
    ...
    module : {
        loaders: [
           { test: /\.styl$/, loader: 'style-loader!css-loader!stylus-loader' },
           { test: /\.css$/, loader: 'style!css' },
        ]
    }
    stylus: {
        use: [bootstrap()],
    },
}
``` 

```
//navbar.styl
@import 'bootstrap/buttons'

.navbar
    height 6.5rem
```

```
//navbar.html
<div class="navbar">
    <span class="btn btn-primary"></span>
</div>

```

When I run my serve and inspect, I see that `btn` is loaded but not compiled (and off course btn-primary is not generated)

I didnt found any other way to configure it with Webpack.

Any idea ?

**Comment by kane-c** [comment]
I haven't tried it with Webpack yet but try adding the Bootstrap directory to your Stylus path instead of using it as a plugin:
```js
module.exports = {
    ...
    module : {
        loaders: [
           { test: /\.styl$/, loader: 'style-loader!css-loader!stylus-loader' },
           { test: /\.css$/, loader: 'style!css' },
        ]
    }
    stylus: {
        paths: ['node_modules/bootstrap-styl'],
    },
}
```

Then you can just import in your Stylus files as normal: `@import 'bootstrap/buttons'`

**Comment by kane-c** [comment]
Looking at [the docs for stylus-loader](https://github.com/shama/stylus-loader), this should do it:

```js
{ test: /\.styl$/, loader: loader: 'css-loader!stylus-loader?paths=node_modules/bootstrap-styl' }
```

**Comment by oric01** [comment]
Yes I tried this, but it has the same effect than the `use` option.
I will ask `stylus-loader` some support and will let you know if I have some news about it.
Thx @kane-c for your current support !

**Comment by kane-c** [comment]
No worries. Good luck!

**Comment by priyankaselvamclara** [comment]
same problem...
ERROR in ./~/css-loader!./~/stylus-loader!./client/app/components/passenger/passenger.styl
Module build failed: TypeError: D:\flydubai-booking-new\src\flydubai.Booking.Web\client\app\components\passenger\passenger.styl:521:1
   517|                   font-size 18px
   518|                   font-weight 400
   519|                   line-height 15px
   520|                   border-bottom 10px
   521|
--------^
   522|

Path must be a string. Received undefined

    at assertPath (path.js:7:11)
    at extname (path.js:889:5)
    at new SourceMapper (D:\flydubai-booking-new\src\flydubai.Booking.Web\node_modules\stylus-loader\node_modules\stylus\lib\visitor\sourcemapper.js:41
:7)
    at Renderer.render (D:\flydubai-booking-new\src\flydubai.Booking.Web\node_modules\stylus-loader\node_modules\stylus\lib\renderer.js:94:9)
    at D:\flydubai-booking-new\src\flydubai.Booking.Web\node_modules\stylus-loader\index.js:149:12
    at tryCatchReject (D:\flydubai-booking-new\src\flydubai.Booking.Web\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (D:\flydubai-booking-new\src\flydubai.Booking.Web\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (D:\flydubai-booking-new\src\flydubai.Booking.Web\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (D:\flydubai-booking-new\src\flydubai.Booking.Web\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (D:\flydubai-booking-new\src\flydubai.Booking.Web\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (D:\flydubai-booking-new\src\flydubai.Booking.Web\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./client/app/components/passenger/passenger.styl 4:14-140 13:2-17:4 14:20-146



neee help

**Comment by priyankaselvamclara** [comment]
same problem,

ERROR in ./~/css-loader!./~/stylus-loader!.
need help

**Comment by JounQin** [comment]
@kane-c Did your source map generate correctly?

https://github.com/shama/stylus-loader/issues/156

**Comment by daniloprates** [comment]
any luck on this?

**Comment by reduxdj** [comment]
any luck on this +1?

**Comment by maxmx** [comment]
We'll accept a PR if someone wants to take this on and it requires a fix in the bootstrap-stylus repo.

The new company I work for is using another framework so I haven't been able to test this against modern build tools.

**Comment by daniloprates** [comment]
I managed to make it work with a small workaround:

https://github.com/daniloprates/thin-starter

main.styl
```css
$icon-font-path = "~bootstrap-styl/fonts/"
@import 'bootstrap';
```

webpack.config.js

```js

var bootstrap = require('bootstrap-styl');

module.exports = {
  entry: {
    a: './src/scripts/main.js',
    b: './src/style/main.styl'
  },
(...)
  stylus: { use: [bootstrap()] },
(...)
};

```

**Comment by kane-c** [comment]
I put together [my webpack sample](https://github.com/maxmx/bootstrap-stylus/issues/121#issuecomment-257125517) and configured it for source maps.

They nearly worked, but I ran into [this bug](https://github.com/shama/stylus-loader/issues/56) with stylus-loader where the browser knows the Stylus file and line but trying to view it just shows a file with `null` as the contents.

Has anyone been able to get source maps working properly?

**Comment by blackendstudios** [comment]
@kane-c adding the query parameter as you suggested worked for me, hope to anyone works to, here's my webpack.config.js

```javascript
module: {
    // rules for modules (configure loaders, parser options, etc.)
    rules: [
      {
        test: /\.html$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: 'html-loader',
            options: {
              minimize: true
            }
          }
        ]
      },
      {
        test: /\.js?$/,
        exclude: [/node_modules/],
        use: ['ng-annotate-loader', 'babel-loader']
      },
      {
        test: /\.css$/,
        exclude: [/node_modules/],
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.styl$/,
        exclude: [/node_modules/],
        use: [
          'style-loader',
          'css-loader',
          'stylus-loader?paths=node_modules/bootstrap-styl'
        ]
      },
      {
        test: /\.(svg|woff|woff2|ttf|eot|ico)$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: 'file-loader?name=src/assets/css/fonts/[name].[hash].[ext]'
          }
        ]
      },
      {
        test: /\.(png|jpe?g|gif)$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: 'file-loader?name=src/assets/img/[name].[ext]'
          }
        ]
      }
    ]
  }
```

**Comment by lightbringer1991** [comment]
I have submitted a PR for this, tested and working on my webpack configuration.

**Comment by jpcmf** [comment]
Can you share the solution @lightbringer1991 ?

**Comment by lightbringer1991** [comment]
@jpcmf it's in the linked PR to this issue https://github.com/maxmx/bootstrap-stylus/pull/132

**Comment by yoyoys** [comment]
When will #132, #133 be merged? nice done.
