### ISSUE TITLE
using with font-awesome-stylus

### ISSUE THREAD

**Issue by fortunado** [maxmx/bootstrap-stylus#93]
Hi,

I've stuck with trying to import bootstrap and font-awesome together
I've tried different import order, and used bootstrap-styl as plugin, and niether one way are not working.
```javascript
$icon-font-path ?= "../../../node_modules/bootstrap-styl/fonts/"
@import bootstrap

$fa-font-path 	?= "../../../node_modules/font-awesome-stylus/fonts/"
@import "font-awesome-stylus/stylus"
```

I got this error:
```javascript
ERROR in ./~/css-loader!./~/postcss-loader!./~/stylus-loader?paths=node_modules!./choboty/app/styles/app.styl
Module build failed: Error: /home/strongloop/node_modules/bootstrap-styl/bootstrap/type.styl:26:42
   22| h1, .h1,
   23| h2, .h2,
   24| h3, .h3
   25|   margin-top $line-height-computed
   26|   margin-bottom ($line-height-computed / 2)
------------------------------------------------^
   27| 
   28|   small,
   29|   .small

cannot perform $line-height-computed / 2
    at "h1" (/home/strongloop/node_modules/bootstrap-styl/bootstrap/type.styl:21:32)

    at Ident.Node.operate (/home/strongloop/node_modules/stylus-loader/node_modules/stylus/lib/nodes/node.js:234:15)
    at Ident.operate (/home/strongloop/node_modules/stylus-loader/node_modules/stylus/lib/nodes/ident.js:155:33)
    at CachedPathEvaluator.Evaluator.visitBinOp (/home/strongloop/node_modules/stylus-loader/node_modules/stylus/lib/visitor/evaluator.js:563:28)
    at CachedPathEvaluator.Visitor.visit (/home/strongloop/node_modules/stylus-loader/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/home/strongloop/node_modules/stylus-loader/node_modules/stylus/lib/visitor/evaluator.js:153:18)
    at CachedPathEvaluator.Evaluator.visitExpression (/home/strongloop/node_modules/stylus-loader/node_modules/stylus/lib/visitor/evaluator.js:626:26)
    at CachedPathEvaluator.Visitor.visit (/home/strongloop/node_modules/stylus-loader/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/home/strongloop/node_modules/stylus-loader/node_modules/stylus/lib/visitor/evaluator.js:153:18)
    at CachedPathEvaluator.Evaluator.visitExpression (/home/strongloop/node_modules/stylus-loader/node_modules/stylus/lib/visitor/evaluator.js:626:26)
    at CachedPathEvaluator.Visitor.visit (/home/strongloop/node_modules/stylus-loader/node_modules/stylus/lib/visitor/index.js:28:40)
 @ ./choboty/app/styles/app.styl 4:14-247 12:19-252
```
`$line-height-computed` is defined.

But if I exclude font-awesome-stylus  - styles compiles ok
```
font-awesome-stylus 1.2.0
bootstrap-styl 4.0.3
webpack 1.7.3
stylus-loader 1.0.0
```
Any help appreciated. Thanks.

**Comment by nw** [comment]
This question isn't really about bootstrap-stylus.

`font-awesome-stylus` has a few issues.

I managed to get this working by doing the following:

```
$fa-font-path = '../../node_modules/font-awesome-stylus/fonts'
@import '../../node_modules/font-awesome-stylus/stylus'
```
Note: my index.styl is located in `client/styles` inside my project hence the `../..` before `node_modules`

However this doesn't resolve the issue with the actual fonts. You need to move the fonts into a directory that matches your public server.

I made this change:

```
$fa-font-path = '/fonts'
```
I added a gulp task to move the fonts into my `public/fonts` folder. I actually did the same for this package too.

The other option is manually control your stylus compiler directly. I played around with using the url define rule to inline the fonts. This resolves the issues however creates a few other problems. 

* You embed all fonts not just the one for a particular browser.
* Older versions of IE can't support larger base64 uris. IE maxes out at 64kb.

**Comment by maxmx** [comment]
Thanks for pitching in  @nw 

Closing issue @fortunado
